FROM tvm-remote-rocm-ubuntu:latest
LABEL maintainer=ajaha004@ucr.edu

ARG CONTROL_PORT="9090"
ARG BUILD_MODE="Debug"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && apt-get -qq install -y environment-modules

COPY ../workloads /workloads

RUN cd /workloads/Inference-server/ \
  && rm -rf build && mkdir build \
  && cd build \
  && cmake -DCMAKE_PREFIX_PATH=/opt/pytorch/torch .. \
  && make -j

RUN cd /workloads/miniMDock/ \
  && rm -rf bin && mkdir bin \
  && . /etc/profile.d/modules.sh \ 
  && ./compile_hip_coe.sh

COPY ../scripts/utils/experiment_runner/workload_runners /workload_runner

RUN cd /workload_runner/ \
    && pip3 install -r requirements.txt

# Start controller service () then keep container running for debug porposes
ENTRYPOINT /usr/local/bin/controller > "/workspace/logs/$(date -Iminutes)_${WORKLOAD}_controller.log" & python3 /workload_runner/workload_runner_target.py