FROM rocm5.7.1-ubuntu20.04:latest
LABEL maintainer=ajaha004@ucr.edu

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y  xxd libzmq3-dev python3 python3-pip linux-tools-generic-hwe-20.04 linux-tools-5.15.0-89-generic

